### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by TechnologyClassroom** [nasan016/webshell#2]
I see you have no LICENSE file for this project. The default is copyright.

I would suggest releasing the code under the GPL-3.0-or-later or AGPL-3.0-or-later license so that others are encouraged to contribute changes back to your project.

**Comment by nasan016** [comment]
I'll definitely add one soon. I don't know much about licenses if I'm being honest but I'll look into it!

**Comment by TechnologyClassroom** [comment]
GitHub tries to make it as easy as possible to understand and apply. Once you make a file named LICENSE, it walks you through the common options and the gist of each one. Let me know if you have any trouble with it.
