### ISSUE TITLE
Enter doesn't do anything on mobile

### ISSUE THREAD

**Issue by TurtleMeds** [nasan016/webshell#3]
Using Oneplus Nord n30 5g with android 13
Brave Browser 1.52.130, Chromium 114.0.5735.198
I've also seen someone else on reddit with the same issue (Android 14, stock Pixel 6 Pro. Firefox 120.1.0 with uBlock Origin installed.

same on Chrome 119.0.6045.194) 

**How to recreate:**
1. Open website
2. Type command
3. Press enter

**What I expect to happen:**
the command executes

**What happens instead:**
nothing, the website doesn't respond

I'm happy to provide any more info if needed. great project!

**Comment by nasan016** [comment]
Hey do you have any idea on how I could test this if I don't have an Android device?

Thanks again for the feedback!

**Comment by TurtleMeds** [comment]
you can use an Android emulation app, such as Bluestacks or WSA if on Windows, or Waydroid if on linux.
